# Generated by Django 4.0.4 on 2022-05-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='access_group',
            fields=[
                ('id', models.AutoField(db_column='group_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Access Group',
                'verbose_name_plural': 'Access Group',
            },
        ),
    ]
