# Generated by Django 4.0.5 on 2022-06-02 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'access_group',
            },
        ),
        migrations.CreateModel(
            name='DeptAll',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_ename', models.CharField(max_length=64, unique=True)),
                ('dept_uname', models.CharField(max_length=64, unique=True)),
                ('copymail', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dept_all',
            },
        ),
        migrations.CreateModel(
            name='FacultyAll',
            fields=[
                ('faculty_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('faculty', models.CharField(blank=True, max_length=30, null=True)),
                ('dept_id', models.IntegerField()),
            ],
            options={
                'db_table': 'faculty_all',
            },
        ),
        migrations.CreateModel(
            name='TitleAll',
            fields=[
                ('title_id', models.AutoField(primary_key=True, serialize=False)),
                ('title_uname', models.CharField(max_length=30, unique=True)),
                ('title_ename', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'title_all',
            },
        ),
        migrations.CreateModel(
            name='UsersAll',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_id', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=6)),
                ('login', models.CharField(max_length=16, unique=True)),
                ('passwd', models.CharField(max_length=40)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('contr_quest', models.CharField(max_length=255)),
                ('contr_answ', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('welcome_msg', models.CharField(blank=True, max_length=255, null=True)),
                ('admin', models.CharField(max_length=1)),
                ('document_id', models.CharField(max_length=16)),
                ('creator', models.CharField(max_length=16)),
                ('operator', models.CharField(max_length=1)),
                ('mgroup_id', models.IntegerField()),
                ('title_id', models.PositiveIntegerField()),
                ('admin_level', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'users_all',
            },
        ),
        migrations.CreateModel(
            name='UsersHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('action', models.CharField(max_length=10)),
                ('creator', models.CharField(max_length=16)),
                ('reason', models.TextField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'users_history',
            },
        ),
        migrations.CreateModel(
            name='UsersAccessGroup',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.usersall')),
                ('desc', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.accessgroup')),
            ],
            options={
                'db_table': 'users_access_group',
                'unique_together': {('user', 'group')},
            },
        ),
    ]
