# Generated by Django 4.0.4 on 2022-05-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dept_all_faculty_all_title_all_users_access_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_group',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='dept_all',
            name='copymail',
            field=models.CharField(blank=True, max_length=50, verbose_name='copymail'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='admin',
            field=models.CharField(blank=True, choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2, verbose_name='admin'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='admin_level',
            field=models.IntegerField(blank=True, max_length=10, verbose_name='admin_level'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='contr_answ',
            field=models.CharField(blank=True, max_length=255, verbose_name='contr_answ'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='contr_quest',
            field=models.CharField(blank=True, max_length=255, verbose_name='contr_quest'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='creator',
            field=models.CharField(blank=True, max_length=16, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='mgroup_id',
            field=models.IntegerField(blank=True, max_length=10, verbose_name='mgroup_id'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='operator',
            field=models.CharField(blank=True, choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2, verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='state',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=10, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='title',
            field=models.CharField(blank=True, max_length=30, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='title_id',
            field=models.IntegerField(blank=True, max_length=10, verbose_name='title_id'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='welcome_msg',
            field=models.CharField(blank=True, max_length=255, verbose_name='welcome_msg'),
        ),
        migrations.AlterField(
            model_name='users_history',
            name='action',
            field=models.CharField(blank=True, choices=[('CREATION', 'CREATION'), ('WARNING', 'WARNING'), ('CLOSING', 'CLOSING'), ('ACTIVATION', 'ACTIVATION'), ('CHPASS', 'CHPASS'), ('EXT_EXPIRE', 'EXT_EXPIRE'), ('CHDATA', 'CHDATA')], default='CREATION', max_length=20, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='users_history',
            name='creator',
            field=models.CharField(blank=True, max_length=16, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='users_history',
            name='ip',
            field=models.TextField(blank=True, max_length=15, verbose_name='ip'),
        ),
        migrations.AlterField(
            model_name='users_history',
            name='reason',
            field=models.TextField(blank=True, verbose_name='reason'),
        ),
    ]
