# Generated by Django 4.0.5 on 2022-06-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_usershistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('action', models.CharField(max_length=10)),
                ('creator', models.CharField(max_length=16)),
                ('reason', models.TextField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'users_history',
            },
        ),
    ]
