# Generated by Django 4.0.5 on 2022-06-05 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_usershistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestorePassword',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('exp_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('temporary_pass', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.usersall')),
            ],
            options={
                'db_table': 'restore_password',
            },
        ),
    ]
