# Generated by Django 4.0.4 on 2022-05-27 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_access_group_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_all',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dept_all'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='title_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.title_all'),
        ),
    ]
