# Generated by Django 4.0.4 on 2022-05-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_users_all_dept_id_alter_users_all_title_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_all',
            name='mgroup_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.access_group'),
        ),
    ]
