# Generated by Django 4.0.4 on 2022-05-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_users_all_mgroup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_all',
            name='admin_level',
            field=models.IntegerField(blank=True, choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3)], max_length=10, verbose_name='admin_level'),
        ),
    ]
