# Generated by Django 4.0.4 on 2022-05-27 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_users_all_admin_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_all',
            name='admin_level',
            field=models.IntegerField(blank=True, choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3)], default='0', max_length=10, verbose_name='admin_level'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='mgroup_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.access_group'),
        ),
    ]
