# Generated by Django 4.0.5 on 2022-06-05 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_restorepassword_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorepassword',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.usersall'),
        ),
    ]
