# Generated by Django 4.0.4 on 2022-05-27 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_users_all_admin_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_all',
            name='contr_answ',
            field=models.CharField(blank=True, default='-', max_length=255, verbose_name='contr_answ'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='contr_quest',
            field=models.CharField(blank=True, default='-', max_length=255, verbose_name='contr_quest'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='creator',
            field=models.CharField(blank=True, default='name', max_length=16, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='dept_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.dept_all'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='phone',
            field=models.CharField(blank=True, default='+380', max_length=30, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='title',
            field=models.CharField(blank=True, default='-', max_length=30, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='title_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.title_all'),
        ),
        migrations.AlterField(
            model_name='users_all',
            name='welcome_msg',
            field=models.CharField(blank=True, default='-', max_length=255, verbose_name='welcome_msg'),
        ),
    ]
