# Generated by Django 4.0.5 on 2022-06-05 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_restorepassword_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestorePassword',
        ),
    ]
