# Generated by Django 4.0.4 on 2022-05-28 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_users_all_admin_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_history',
            name='id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.dept_all'),
        ),
    ]
