# Generated by Django 4.0.4 on 2022-05-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_users_history_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_all',
            name='dept_id',
            field=models.IntegerField(verbose_name='dept_id'),
        ),
        migrations.AlterField(
            model_name='users_access_group',
            name='group_id',
            field=models.IntegerField(verbose_name='group_id'),
        ),
        migrations.AlterField(
            model_name='users_history',
            name='id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.users_all'),
        ),
    ]
