# Generated by Django 4.0.5 on 2022-06-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_restorepassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestorePassword',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.PositiveIntegerField()),
                ('exp_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('temporary_pass', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'restore_password',
            },
        ),
    ]
