# Generated by Django 4.0.4 on 2022-05-28 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_faculty_all_dept_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_history',
            name='id',
            field=models.ForeignKey(db_column='user_id', default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.users_all'),
        ),
    ]
