# Generated by Django 4.0.4 on 2022-05-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_users_history_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_history',
            old_name='id',
            new_name='user_id',
        ),
    ]
