# Generated by Django 4.0.4 on 2022-05-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_users_history_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_history',
            old_name='user_id',
            new_name='id',
        ),
    ]
