# Generated by Django 4.0.4 on 2022-05-28 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_user_id_users_history_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_history',
            name='id',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.users_all'),
        ),
    ]
