# Generated by Django 4.0.4 on 2022-05-28 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_users_history_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_history',
            name='id',
        ),
        migrations.AddField(
            model_name='users_history',
            name='user_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.users_all'),
        ),
    ]
