# Generated by Django 4.0.4 on 2022-05-28 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_users_history_id_users_history_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_history',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.users_all'),
        ),
    ]
