# Generated by Django 4.0.4 on 2022-05-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_users_history_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_history',
            name='user_id',
        ),
        migrations.AddField(
            model_name='users_history',
            name='id',
            field=models.IntegerField(db_column='user_id', default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faculty_all',
            name='dept_id',
            field=models.IntegerField(max_length=10, verbose_name='dept_id'),
        ),
        migrations.AlterField(
            model_name='users_access_group',
            name='group_id',
            field=models.IntegerField(max_length=10, verbose_name='group_id'),
        ),
    ]
