# Generated by Django 4.0.4 on 2022-05-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_users_history_user_id_users_history_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_history',
            name='id',
        ),
        migrations.AddField(
            model_name='users_history',
            name='user_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
