# Generated by Django 4.0.4 on 2022-05-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_users_history_id_users_history_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_history',
            name='user_id',
        ),
        migrations.AddField(
            model_name='users_history',
            name='id',
            field=models.AutoField(db_column='user_id', default=0, primary_key=True, serialize=False),
        ),
    ]
