# Generated by Django 4.0.4 on 2022-05-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_users_history_user_id_users_history_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users_history',
        ),
    ]
