# Generated by Django 4.0.4 on 2022-05-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_users_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users_history',
        ),
    ]
