# Generated by Django 4.0.4 on 2022-05-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_delete_users_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='users_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('action', models.CharField(blank=True, choices=[('CREATION', 'CREATION'), ('WARNING', 'WARNING'), ('CLOSING', 'CLOSING'), ('ACTIVATION', 'ACTIVATION'), ('CHPASS', 'CHPASS'), ('EXT_EXPIRE', 'EXT_EXPIRE'), ('CHDATA', 'CHDATA')], default='CREATION', max_length=20, verbose_name='Action')),
                ('creator', models.CharField(blank=True, max_length=16, verbose_name='creator')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('ip', models.TextField(blank=True, max_length=15, verbose_name='ip')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.users_all')),
            ],
            options={
                'verbose_name': 'users history',
                'verbose_name_plural': 'users history',
            },
        ),
    ]
