# Generated by Django 4.0.4 on 2022-05-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_users_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_all',
            name='passwd',
            field=models.CharField(max_length=100, verbose_name='passwd'),
        ),
    ]
