# Generated by Django 4.0.4 on 2022-05-29 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_users_all_passwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_all',
            name='title_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.title_all'),
        ),
    ]
