# Generated by Django 4.0.4 on 2022-05-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_users_all_admin_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_all',
            name='dept_id',
            field=models.IntegerField(verbose_name='dept_id'),
        ),
        migrations.AlterField(
            model_name='users_access_group',
            name='group_id',
            field=models.IntegerField(verbose_name='group_id'),
        ),
    ]
