# Generated by Django 4.0.4 on 2022-05-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_faculty_all_dept_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title_all',
            name='id',
        ),
        migrations.AddField(
            model_name='title_all',
            name='title_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
