# Generated by Django 4.0.4 on 2022-05-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_title_all_id_title_all_title_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title_all',
            name='title_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
