# Generated by Django 4.0.4 on 2022-05-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_title_all_title_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title_all',
            name='title_id',
        ),
        migrations.AddField(
            model_name='title_all',
            name='id',
            field=models.AutoField(db_column='title_id', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
