# Generated by Django 4.0.4 on 2022-05-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_title_all_title_id_title_all_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_all',
            name='title_id',
            field=models.CharField(blank=True, choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2, verbose_name='operator'),
        ),
        migrations.DeleteModel(
            name='title_all',
        ),
    ]
