# Generated by Django 4.0.4 on 2022-05-29 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_users_all_title_id_delete_title_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='title_all',
            fields=[
                ('id', models.AutoField(db_column='title_id', primary_key=True, serialize=False)),
                ('title_uname', models.CharField(max_length=30, verbose_name='title_uname')),
                ('title_ename', models.CharField(max_length=30, verbose_name='title_ename')),
            ],
            options={
                'verbose_name': 'Title All',
                'verbose_name_plural': 'Title All',
            },
        ),
        migrations.AlterField(
            model_name='users_all',
            name='title_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.title_all'),
        ),
    ]
